# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:t4ANsyFupdX5u4trFRO1sOnvuP/8tbKq1DxbfkvqeE4RqT0QrWBz3A==,iv:F8v15gJKB8MS3hwvh8Xt9VdDNn4fFt6wqiNEEGJM1Qc=,tag:/rdA892pebzB0PAEWkZIfw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dmarwqpnts3xtf80kl0940yggjnzqpum62je4znmww7yn8uf5sesq54n92
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMWdMdURvN2pDVGtLQWhw
        ckJSQVNodnBVTWNicVZLamYzaWlicFN4eVUwCm8rSkNIMjJnUjg1ZEE2T0Y4Y25X
        aTNHOFJLN3ZzWUxybjYzQk8xQ25PMkEKLS0tIGV0TW5qN1FRVk1oRGJhRlJlMUlU
        MGUyUkZhbHk1R2xYTk9zWkNUMndubEkKgnZQT0oyWt6ha5+bKh4A+awFWXIgVITe
        WlEaLES6BLJ4J6O+kJkOt5JhDJtNOPJoEKBwagLC1KSE2BnhTx+VVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T13:27:26Z"
  mac: ENC[AES256_GCM,data:vh149rF8047rXeUE5m97BtOoTHrKHxasBzWg4g2J9B0s/JLdfwwnuYP2Uw3wTrUGhPEx7FvMHpHkXE7Cbw8XZNxKhzeTwZvJnejv2iE4ezGFuvYB0Kpptel+MB4G4zdJsEG/frmDBGEJgZj/jbTh0osO+YXUiBs/xg7nMw0xskM=,iv:BBwg8xkbDAIDUqO8OVUTRwuefrzsmskDMCgo51YTDz0=,tag:d3sAA5Vpdn+SuFvVuRy3ZQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
