# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:L/lc7iAKJevZWsMAG0D8cnpQPfQ0cDKxq8GHePjgDgUcQpm5S7ak6A==,iv:xgB3MPi8OuhgkfjHln3osJDt47zANJM8EuIbMResPGE=,tag:NTnDqEBPV/wn56eCmqU+9w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dmarwqpnts3xtf80kl0940yggjnzqpum62je4znmww7yn8uf5sesq54n92
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM3FQVHZOTXFTRGxsbm16
        NUhXTWtOUlJDQzlpVXZneHBsVDhTblp4NGhRCkpudFh3aHRlOEFzN2s2OW5ZZFFY
        OGpTeDhPN2EwSmhwNk9aRFVpUk5BZkEKLS0tIElTTXZxZkhWajhQYjdkTFpJVFM0
        cytHUFpIVU1iSGFPYXVkY2phRXBjUEkKphLitVporddWQU7QWXRfdMwHqxVMzLve
        2p3kL77XkRgYRIWvgjeGlYw4zKIcv5Yz0QtyxwdC256e589KRKinMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T14:05:30Z"
  mac: ENC[AES256_GCM,data:0IWANi29J6s9LzwNdz6SmcHJVs+dKOphZ38/53yDR0+VNr/Z2qwqpKsCkfQG8dp7EdGCVBkbhrbMLFV4Nrdy/pfcxmb9OijkKJfLbEbik61UZhN/Mvsx7HHePAb24jf6dTxbzq+fExP9R+NAqPHeLuq+ENoqrHLTotc/E8Pzi+A=,iv:M12CJODVFRcaKha8CtuoalDEb3igwJmWFy8bOqEGi3I=,tag:bzRw+3BSw2shP8M+zRzaLw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
