# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:9p5zOwP89z1oiOEITVom0jwt7I1tO1AprhWCmRHFUTpLfXa4da9THg==,iv:kvVIpzfhy3lU8fBHJN43CNFzOhq+6WUU3toWy4fUWDY=,tag:iCjGkuXjUynJfUNdRbX5uA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dmarwqpnts3xtf80kl0940yggjnzqpum62je4znmww7yn8uf5sesq54n92
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc1dJclI0ODlVdFRnZzhu
        ZXl4VFZXOXNTbWFaWHVBTGVYRDMveXBoUGh3CkQrQlZCMjkzYmZFdytnWE5UaWhW
        bnJxZ3ZxSnE0cmdZMHFqR1dNZFFjb1kKLS0tIE84TmQvaWdBNDJBN2JzdmFnQmVR
        SHl3ZDZBSmlVb2tRRTZCUVcvKzFtS2sKXlAkyIoWFGA1C4NH8bnh1EtiXAkyhPtn
        Z9SXWd07QWeoG2fMhQWJno4u4xAuTztnqSwtaLM3klUmZ8m7g4bOkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T11:19:16Z"
  mac: ENC[AES256_GCM,data:yDwRfxOwkWf7ckfg8D6f5e5VZgAm99YR2yh8kFch17bql8k3mQaul0q/zZYsOdLoba8Wvh4yBiu5Ij3F8E1atZDxEluasWD29Bw+ZEd3HhMKybVoabPWZOlGcUbMbNQNS5zeX0zvwStjHTTSnXmXj+RHskstnjrj/p4602Bow1k=,iv:zzH9J3rWJvk9g+18AWPOxzBWpv1C/aTrKY75G+bfErU=,tag:9G7rdsxGMgtaZW9IFvaDlg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
